# Generated by Django 6.0.6 on 2026-06-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectobd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservacion',
            name='acomodo_sillas',
            field=models.CharField(choices=[('HERRADURA', 'Herradura'), ('SALON', 'Salón (solo sillas)'), ('AULA', 'Aula (sillas y mesas)')], default='SALON', max_length=20),
        ),
    ]
